#!/bin/bash
# INFRA NOTE (2026-06-30): Caddy trusted_proxies is a GLOBAL-ONLY directive.
# Lives in /etc/caddy/Caddyfile under the global options block:
#   { servers { trusted_proxies static <CF ranges> } }
# It is NOT a per-site importable snippet/macro — `import cloudflare_trust`
# in a vhost block fails validation ("unrecognized directive"). Fixed after
# caddy-proxmox jail banned a Cloudflare edge IP (172.70.153.176) instead of
# the real client IP, because client_ip in JSON logs wasn't resolving from
# X-Forwarded-For/Cf-Connecting-Ip without trusted_proxies configured.
#
# INFRA NOTE (2026-07-12): Certsite uses an external stylesheet (style.css) unlike
# index.html and status.html which have inline <style> blocks. On mobile,
# CSS rules in the external file can be overridden or delayed, causing elements
# like the scroll-progress bar to not render. Fix: use inline style="" directly
# on the element with z-index:9999. When adding visual effects to certsite,
# always put critical above-the-fold styles inline on the HTML element itself,
# not just in style.css.
#
# INFRA NOTE (2026-06-30): Live status dashboard (status.html + status.json)
# added. status.json is generated by /opt/telegram-bot/generate_status.py
# (hourly cron on Telegram LXC), NOT edited here directly. It overwrites
# status.json with fresh data each run; site-helper.sh just picks up
# whatever is on disk when you deploy. Run generate_status.py manually
# from /opt/telegram-bot/ if you want a fresh snapshot before deploying.
SITE_DIR="/opt/js-lab-web"
cd "$SITE_DIR" || exit 1
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'
status() {
echo
echo "========================================"
echo " JS-LAB WEBSITE STATUS"
echo "========================================"
echo
echo -e "${BLUE}Location:${NC} $SITE_DIR"
echo
echo -e "${BLUE}Files${NC}"
ls -lh
echo
echo -e "${BLUE}Git${NC}"
git status --short
echo
echo "Branch : $(git branch --show-current)"
echo "Commit : $(git rev-parse --short HEAD)"
echo
echo -e "${BLUE}Last commits${NC}"
git log --oneline -5
echo
echo -e "${BLUE}HTML${NC}"
python3 <<'PYEOF'
from pathlib import Path
import re
html = Path("index.html").read_text()
print("Sections :", html.count("<section"))
print("Images   :", html.count("<img"))
print("Links    :", html.count("<a "))
print("Size     :", len(html), "bytes")
PYEOF
echo
echo -e "${BLUE}Status dashboard${NC}"
if [[ -f "status.json" ]]; then
    python3 <<'PYEOF'
import json
from pathlib import Path
try:
    data = json.loads(Path("status.json").read_text())
    print("Last updated :", data.get("updated", "unknown"))
    svc = data.get("services", {})
    for k, v in svc.items():
        print(f"  {k:14s}: {v}")
except Exception as e:
    print("Could not parse status.json:", e)
PYEOF
else
    echo -e "${RED}✗${NC} status.json not found"
fi
echo
echo -e "${BLUE}Required files${NC}"
for f in index.html js-lab-logo-round.png site-helper.sh status.html
do
    if [[ -f "$f" ]]; then
        echo -e "${GREEN}✓${NC} $f"
    else
        echo -e "${RED}✗${NC} $f"
    fi
done
echo
}
backup() {
mkdir -p backups
FILE="backups/index-$(date +%F-%H%M%S).html"
cp index.html "$FILE"
echo -e "${GREEN}Backup created:${NC}"
echo "$FILE"
}
deploy() {
git add .
git commit -m "${1:-Website update}"
git push
}
replace() {
python3 <<PYEOF
from pathlib import Path
old = """$1"""
new = """$2"""
p = Path("index.html")
html = p.read_text()
count = html.count(old)
html = html.replace(old,new)
p.write_text(html)
print(f"Replaced {count} occurrence(s).")
PYEOF
}
mobile()
{
echo "Applying mobile optimization..."
# backup first
mkdir -p backups
cp index.html "backups/index-mobile-$(date +%F-%H%M%S).html"
python3 <<'PY'
from pathlib import Path
html = Path("index.html").read_text()
# inject mobile CSS if not exists
if "MOBILE-FIX" not in html:
    fix = """
<style id="MOBILE-FIX">
@media (max-width: 768px), (pointer: coarse) {
    * {
        animation: none !important;
        transition: none !important;
    }
    .hero, .container {
        transform: none !important;
        filter: none !important;
    }
}
</style>
"""
    html = html.replace("</head>", fix + "\n</head>")
Path("index.html").write_text(html)
print("Mobile patch applied")
PY
}
refresh_status() {
echo "Regenerating status.json via /opt/telegram-bot/generate_status.py..."
/opt/telegram-bot/venv/bin/python3 /opt/telegram-bot/generate_status.py
if [[ ! -f "status.json" ]]; then
    echo -e "${RED}status.json not found after run — check generate_status.py output${NC}"
    return 1
fi
echo -e "${GREEN}status.json refreshed${NC}"
OLD_CONTENT=$(git show HEAD:status.json 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); d.pop('updated',None); print(json.dumps(d,sort_keys=True))" 2>/dev/null)
NEW_CONTENT=$(python3 -c "import json; d=json.load(open('status.json')); d.pop('updated',None); print(json.dumps(d,sort_keys=True))")
if [[ "$OLD_CONTENT" != "$NEW_CONTENT" ]]; then
    git add status.json
    git commit -m "Auto-update status.json $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    git push
    echo -e "${GREEN}status.json committed and pushed — Cloudflare Pages will redeploy${NC}"
else
    echo "No substantive changes to status.json, skipping commit"
fi
}
help_menu() {
echo
echo "JS-LAB Helper"
echo
echo "Usage:"
echo
echo "./site-helper.sh status"
echo "./site-helper.sh backup"
echo "./site-helper.sh deploy \"message\""
echo "./site-helper.sh replace \"OLD\" \"NEW\""
echo "./site-helper.sh refresh-status"
echo
}
case "$1" in
status)
status
;;
backup)
backup
;;
deploy)
shift
deploy "$*"
;;
replace)
replace "$2" "$3"
;;
mobile)
mobile
;;
refresh-status)
refresh_status
;;
*)
help_menu
;;
esac
